package app

import (
	"testing"
)

func TestCreate(t *testing.T) {
	t.Run("should return autogenerated ID", func(t *testing.T) {
		store := &AccountStore{
			maxID:       0,
			dataStorage: make(map[uint64]Account),
		}

		want := uint64(1)
		got := store.Create("", "", 0)

		if want != got {
			t.Errorf("want %d; got %d", want, got)
		}
	})

	t.Run("should return last possible ID", func(t *testing.T) {
		store := &AccountStore{
			maxID:       90,
			dataStorage: make(map[uint64]Account),
		}

		want := uint64(91)
		got := store.Create("", "", 0)

		if want != got {
			t.Errorf("want %d; got %d", want, got)
		}
	})
}

func TestGetBalance(t *testing.T) {
	t.Run("should return account balance", func(t *testing.T) {
		store := &AccountStore{
			maxID:       90,
			dataStorage: make(map[uint64]Account),
		}

		want := uint64(10)
		newAccID := store.Create("", "", 10)
		got, _ := store.GetBalance(newAccID)

		if want != got {
			t.Errorf("want %d; got %d", want, got)
		}
	})
}